main: me.jos.hats.Main
name: Hats
version: 1.0.0
author: Jos
api-version: 1.19

commands:
  hats:
    description: Hats Command

permissions:
  hatcosmetics.reload:
    description: Allows you to reload the plugin's config.
    default: op
  hatcosmetics.hat:
    description: Allows use of hat in permission.
    default: op
  hatcosmetics.equip.other:
    description: Allows sender to equip hat for online player.
    default: op
  hatcosmetics.unequip.other:
    description: Allows sender to unequip hat from online player.
    default: op